version: "3.5"
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
  redispeech:
    build: .
    container_name: redispeech
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
networks:
 default:
  name: redis
