FROM python:3

WORKDIR /redispeech

# ENV MODEL_PACKAGE https://github.com/mozilla/DeepSpeech/releases/download/v0.5.1/deepspeech-0.5.1-models.tar.gz
# ADD ${MODEL_PACKAGE} models.tar.gz
# ENV MODEL_PACKAGE models/deepspeech-0.5.1-models.tar.gz
# COPY ${MODEL_PACKAGE} models.tar.gz
# RUN mkdir ../models && tar xvfz models.tar.gz --directory ../models && rm models.tar.gz

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY python/src src
COPY config.json config.json

CMD [ "python", "./src/main.py", "config.json" ]
