[package]
name = "rust"
version = "0.1.0"
authors = ["Jack Frost <j4qfrost@gmail.com>"]
edition = "2018"

[dependencies]
deepspeech = { git = "https://github.com/RustAudio/deepspeech-rs.git" }
# audrey = "0.2"
serde = "1.0.94"
serde_json = "1.0.40"
byteorder = "1.2.2"
lapin-async = "0.22.0"
