version: "3.5"
services:
  redispeech-rust:
    image: redispeech-rust
    # build: .
    container_name: redispeech
    environment:
      RUST_BACKTRACE: 1
      BROKER_HOST: broker
      BROKER_PORT: 5672
    volumes:
      - type: bind
        source: ../models
        target: /models
    restart: on-failure
    depends_on:
      - broker
  broker:
    image: rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5


networks:
 default:
  name: broker
